### PR TITLE
Implement support for some basic attributes for the windows terminal.

### LINKED ISSUE #60: Basic attribute support for Windows systems.
AFAIK, the windows terminal does support attributes, such as bold, but it doesn't support a lot of *nix ones.

https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences

Is it a good idea to see if we can implement partial attributes?

### PR DESCRIPTION
**Pull request by Jezza**
Closes #60.

### CODE REVIEW

**Comment by Jezza** [comment]
You'll probably notice that it doesn't have the full list of values that windows supports as methods, and that's because of how crossterm constructs styles and what the other windows' values are used for.

The values I've omitted, but added explicit members in the enum for are "reset" values, and due to how the styles are constructed, it you can't really construct a line that contains multiple "on"s and "off"s.
Eg, you can't say `style("Introducing ").bold().text("Me").reset().text(" and I.")` which would output something like "Introducing **Me** and I."
The ObjectStyles in crossterm don't seem to be built that way, so it makes no sense to add explicit support for the values as methods.
The values themselves are there in the enum, so you could conceivably, chain together multiple object styles, printing them out one by one, and then in that case, the reset would come in handy, but at that point, it might be easier just to wrap that with your own thing....

**Comment by Jezza** [comment]
Look back, I think a better solution to this might be doing what Std does.  
Have system specific modules, and then just export those based on the system.  
That way the user can still access attributes for other systems, as it is possible that someone can use this library for sending terminal seqs over the wire.

**Comment by Jezza** [comment]
Yeah, but do it in a controlled fashion.  

`format!("{}Inverted{}Normal", Attribute::Inverted, Attribute::Reset)`

It doesn't stop people from being stupid, but it didn't do that before.
It just makes composing things easier.

**Comment by TimonPost** [comment]
Jup that totally does it, however, for now, I am fine whit those changes. This should become another PR.

**Pull request merged**
