### PR TITLE
Fix Windows terminal size (#170)

### PR DESCRIPTION
**Pull request by natbraun**
This change is [Reviewable](https://reviewable.io/reviews/timonpost/crossterm/176)

### CODE REVIEW

**Comment by TimonPost** [comment]
Thanks for your work! Looks good to me, I forgot about that other place that was getting the screen size, good that you noticed that place as well. Actually `WinApiTerminal::terminal_size()` should use `get_terminal_size` function as well, instead of having duplicated code. Would be nice, if you could fix that in this PR, otherwise we can just merge it, and I make an issue for it.

**Comment by natbraun** [comment]
Just pushed a new revision

**Comment by natbraun** [comment]
By the way, in order to be complete, we also have to make **setting** the size consistent across platforms and 1-based.

**Comment by TimonPost** [comment]
Right, let me create a new issue for that

**Pull request merged**
