### PR TITLE
clean up

### PR DESCRIPTION
**Pull request by TimonPost**
clean up

### CODE REVIEW

**Comment by TimonPost** [comment]
I ran `cargo fix` and this PR was the result. I agree that you could have the name there since we than know that those variables exists but they could be removed. @jojolepro have you any specific reason why having `_` is better.  I once heard that "when using `_` no allocation" is made you know if that statement is right?

**Comment by jojolepro** [comment]
Since those are in example files, _name makes more sense. If it was in crossterm's implementation then _ could fit better. Its mostly preferences though.

**Comment by TimonPost** [comment]
@jojolepro A I see indeed it is just preference I removed the `_` before variables in the examples. In the lib I left it as it is.

**Comment by TimonPost** [comment]
Yea I get your point. It looks cleaner without `_` maybe if I do `#![allow(dead_code)]` for the examples it will be fixed. And I can have normal variable names.

**Pull request merged**
