### PR TITLE
Execute all tests on CI + warnings/errors cleanup

### LINKED ISSUE #205: Travis - Not all tests are executed
`.travis.yml` does contain following lines:

```bash
cargo fmt -- --check
cargo test -- --nocapture --test-threads 1
```

But these commands check formatting / test the `crossterm` crate only. An example - modify `crossterm_terminal/examples/terminal.rs` (make it not compilable) and then run `cargo test -- --nocapture --test-threads 1`. It passes. Same applies to formatting, etc.

### PR DESCRIPTION
**Pull request by zrzka**
Till #215 settles down (GH Actions). It's failing now, because #212 isn't merged yet. Once #212 will be merged, Linux & macOS builds will pass. I'll fix `crossterm_winapi` issues in another PR and then everything will pass.

Fixes #205

### CODE REVIEW

**Comment by TimonPost** [comment]
https://travis-ci.org/TimonPost/crossterm/jobs/584970770#L636

**Comment by zrzka** [comment]
Going to rebase and will apply #217 changes to this PR, because it's a nightmare to have all these small PRs waiting one for another to pass all the tests.

**Comment by zrzka** [comment]
@TimonPost can you please enable [Auto cancel pull request builds](https://docs.travis-ci.com/user/customizing-the-build/#building-only-the-latest-commit)?

**Comment by TimonPost** [comment]
I checked it, but it is already enabled

**Comment by zrzka** [comment]
Thanks for checking. I had 4 commits in the queue at one time and I thought that this is not enabled. It must Travis CI quirk.

**Comment by zrzka** [comment]
@TimonPost finally [green](https://travis-ci.org/TimonPost/crossterm/builds/585150377).

## Status

* Rust stable is passing
* Rust nightly is failing (allowed, informative)
  * It's failing on `rustfmt` on all three platforms
* Zero warnings

## Ignored tests & no_run examples

To achieve this, I had to ignore 5 tests a 1 example. All are cursor or resize related, which is expected.

### `#[ignore]`

* `crossterm_terminal/src/terminal/test.rs - winapi_tests::resize_winapi`
* `crossterm_terminal/src/terminal/test.rs - resize_ansi`
* `crossterm_winapi/src/console_mode.rs - test::set_get_mode`
* `crossterm_cursor/src/cursor/test.rs - reset_safe_ansi`
* `crossterm_cursor/src/cursor/test.rs - goto_ansi`

### Doc example `no_run`

* `crossterm_terminal/src/terminal/terminal.rs - Terminal::exit`

## Proposal

* Merge this PR to execute everything on CI
* Keep the `#[ignore]` & `no_run`
  * Already marked with TODOs
  * You can run all (+ ignored) tests on your machine by adding `--ignored` (`cargo test`)

**Comment by TimonPost** [comment]
Sounds like a good idea, resizing caused weird behavior in the terminal as spoken of before. In my opinion, we should just create one issue for all failing tests, just to keep the things together and have less noise in the issue list.

**Pull request merged**
